language: smalltalk

sudo: false

os:
  - linux
  - osx
  
smalltalk:
  - Pharo64-alpha
  - Pharo64-6.1
  - Pharo-alpha
  - Pharo-6.1

before_install:
- eval "$(ssh-agent)"
- ssh-keyscan github.com >> ~/.ssh/known_hosts
- ssh -T git@github.com || echo "Ok"

env:
  matrix:
    - CI_FILE=.smalltalk.ston
    - CI_FILE=.stress.smalltalk.ston
    
script:
  - travis_wait "$SMALLTALK_CI_HOME/run.sh" ${CI_FILE}